image:
  repository: improbable/thanos
  tag: master-2018-10-29-8f247d6
  pullPolicy: IfNotPresent
  
gcs:
  bucket: pipeline-thanos

store:
  enabled: true
  replicaCount: 1
  monitoring:
    enabled: true
  http:
    port: 10902
  grpc:
    port: 10901
  logLevel: debug

query:
  enabled: true
  replicaCount: 1
  monitoring:
    enabled: true
  grpc:
    port: 10901
  http:
    port: 10902
  logLevel: debug

compact:
  enabled: true
  monitoring:
    enabled: true
  http:
    port: 10902
  logLevel: debug

cluster:
  address: 0.0.0.0
  port: 10900

objstore:
  configFile: "bucket.yaml"
  provider: gcs

  # NOTE These values are present for backwards compatibility, but should
  # be removed at some later date in favor of gcs.credentials and
  # gcs.bucketName below.
  bucketName: ""
  gcsCredentials: ""

  gcs:
    credentials: ""
    bucketName: ""

  s3:
    accessKey: ""
    secretKey: ""
    bucketName: ""
    endpoint: ""
    insecure: false
    signatureVersion2: false
    encryptSse: false
    putUserMetadata: {}
    httpConfig:
      idleConnTimeout: 0s
      insecureSkipVerify: false

replicaLabelName: replica

#prometheus:
#  enabled: false
#  thanosSidecar:
#    enabled: true
